language: php

php:
  - 5.6
  - 7.0
  - hhvm

matrix:
    allow_failures:
        - php: hhvm

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - if [ $(phpenv version-name) != "7.0" ]; then vendor/bin/phpunit; fi
  - if [ $(phpenv version-name)  == "7.0" ]; then vendor/bin/phpunit --coverage-clover=build/coverage.clover; fi

after_script:
  - if [ $(phpenv version-name) == "7.0" ]; then wget https://scrutinizer-ci.com/ocular.phar -O build/ocular.phar; fi
  - if [ $(phpenv version-name) == "7.0" ]; then php build/ocular.phar code-coverage:upload --format=php-clover build/coverage.clover; fi